# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.1.0"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
awsCdk = "2.173.0"
constructs = "10.4.2"
micronaut = "4.7.6"
micronautAws = "4.8.0"
micronautSerde = "2.11.0"
ksp = "2.1.0-1.0.29"
kotest = "5.9.1"

[libraries]
micronaut-runtime = { module = "io.micronaut:micronaut-runtime", version.ref = "micronaut" }
micronaut-inject-kotlin = { module = "io.micronaut:micronaut-inject-kotlin", version.ref = "micronaut" }
micronaut-function-aws = { module = "io.micronaut.aws:micronaut-function-aws", version.ref = "micronautAws" }
micronaut-aws-lambda-events-serde = { module = "io.micronaut.aws:micronaut-aws-lambda-events-serde", version.ref = "micronautAws" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson", version.ref = "micronautSerde" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor", version.ref = "micronautSerde" }
micronaut-test-kotest5 = { module = "io.micronaut.test:micronaut-test-kotest5", version = "4.5.0" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
awsCdkLib = { module = "software.amazon.awscdk:aws-cdk-lib", version.ref = "awsCdk" }
awsLambdaEvents = { module = "com.amazonaws:aws-lambda-java-events", version = "3.15.0" }
constructs = { module = "software.constructs:constructs", version.ref = "constructs" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
awsCdk = ["awsCdkLib", "constructs"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
micronaut-application = { id = "io.micronaut.application", version = "4.4.4" }
micronaut-library = { id = "io.micronaut.library", version = "4.4.4" }