### Create User
POST {{host}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "phoneNumber": "+15145559614",
  "password": "Big<Secret!>33"
}

### Create Duplicate User
POST {{host}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "phoneNumber": "+15145559614",
  "password": "<Secret!>"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 409, "Response status is not 409");
    });
%}

### Get User by ID
GET {{host}}/users/84688428-9031-70c4-0a3c-082a96d481f0

### Get User by Email
GET {{host}}/users/email/john@example.com

### Authenticate User
POST {{host}}/users/email/john@example.com/authenticate
Content-Type: application/json

{
  "password": "Big<Secret!>33"
}

### Update User
PUT {{host}}/users/84688428-9031-70c4-0a3c-082a96d481f0
Content-Type: application/json

{
  "name": "John Updated",
  "email": "john2@example.com",
  "phoneNumber": "+15145559614"
}

### Get User Not Found
GET {{host}}/users/non-existent-id

### Unknown Path
GET {{host}}/unknown

### Delete User
DELETE {{host}}/users/84688428-9031-70c4-0a3c-082a96d481f0

### Method Not Allowed
GET {{host}}/users
