### Create User
POST {{host}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "phoneNumber": "+15145559614",
  "password": "<Secret!>"
}

### Create Duplicate User
POST {{host}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "phoneNumber": "+15145559614",
  "password": "<Secret!>"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 409, "Response status is not 409");
    });
%}

### Get User by ID
GET {{host}}/users/{{user_id}}

### Get User by Email
GET {{host}}/users/email/john@example.com

### Get User Not Found
GET {{host}}/users/non-existent-id

### Unknown Path
GET {{host}}/unknown

### Method Not Allowed
GET {{host}}/users
