### Create Organisation
POST {{host}}/organisations
Content-Type: application/json

{
  "name": "Acme Corp"
}

### Get Organisation by ID
GET {{host}}/organisations/84688428-9031-70c4-0a3c-082a96d481f0

### Get All Organisations
GET {{host}}/organisations

### Update Organisation
PUT {{host}}/organisations/84688428-9031-70c4-0a3c-082a96d481f0
Content-Type: application/json

{
  "name": "Acme Corporation"
}

### Delete Organisation
DELETE {{host}}/organisations/84688428-9031-70c4-0a3c-082a96d481f0

### Add Participant
POST {{host}}/organisations/84688428-9031-70c4-0a3c-082a96d481f0/participants
Content-Type: application/json

{
  "participantId": "349071c8-2748-4e89-9a25-c63e2c3666b6",
  "role": "admin"
}

### Remove Participant
DELETE {{host}}/organisations/84688428-9031-70c4-0a3c-082a96d481f0/participants/349071c8-2748-4e89-9a25-c63e2c3666b6
